version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: telegram-bot-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
        - postgres-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    volumes:
      - telegram-bot-service-db-data:/var/lib/postgresql/data
    depends_on:
      - postgres
    networks:
      - postgres-db

volumes:
  telegram-bot-service-db-data:

networks:
  postgres-db:
    driver: bridge