localhost: localhost

spring:
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5401/${spring.application.name}
    username: root
    password: root
  jpa:
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka