
spring:
  config:
    import: configserver:http://config-server:8888
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:telegram-bot-db}/${spring.application.name}
    username: root
    password: root
  jpa:
    show-sql: false
  rabbitmq:
    host: localhost
    port: 15672
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka