package org.memorizing.model.menu;

public enum EMode {
    FORWARD_TESTING_MODE,
    FORWARD_SELF_CHECK_MODE,
    FORWARD_MEMORIZING_MODE,
    BACKWARD_TESTING_MODE,
    BACKWARD_SELF_CHECK_MODE,
    BACKWARD_MEMORIZING_MODE,
}
