package org.memorizing.model.menu;

public enum ERegularCommand {
    ADD_CARD_STOCK,
    UPDATE_CARD_STOCK,
    DELETE_CARD_STOCK,

    START_STUDYING,

    START_FORWARD_TESTING,
    START_BACKWARD_TESTING,
    START_FORWARD_SELF_CHECK,
    START_BACKWARD_SELF_CHECK,
    START_FORWARD_MEMORIZING,
    START_BACKWARD_MEMORIZING,

    SHOW_CARDS,
    ADD_CARD,
    UPDATE_CARD,
    DELETE_CARD

}
