create table card_stock_history
(
    id             int8 generated by default as identity,
    card_stock_id  int4,
    studying_state varchar(255),
    user_state_id  int4,
    primary key (id)
);

create table user_state
(
    id             int4 generated by default as identity,
    card_id        int4,
    card_stock_id  int4,
    current_menu   varchar(255),
    studying_state TEXT,
    primary key (id)
);

create table user_state_studying_history
(
    user_state_id       int4 not null,
    studying_history_id int8 not null
);

create table users
(
    id            int4 generated by default as identity,
    chat_id       int8,
    name          varchar(255),
    storage_id    int4,
    user_state_id int4,
    primary key (id)
);

alter table if exists card_stock_history
    add constraint UK_5h3ujls235aophc8lfte6r1v0 unique (card_stock_id);
alter table if exists user_state_studying_history
    add constraint UK_b0yli25y7ukxqm4lkqdn74hu9 unique (studying_history_id);
alter table if exists users
    add constraint UK_8xpfvbvc9tew2viqgf2mivqr6 unique (user_state_id);
alter table if exists card_stock_history
    add constraint FKq17yfr1wa8bkyb394d6ocwx8u foreign key (user_state_id) references user_state;
alter table if exists user_state_studying_history
    add constraint FKeqnrpttnqinfi76cnqxo3kk41 foreign key (studying_history_id) references card_stock_history;
alter table if exists user_state_studying_history
    add constraint FKesyap2bby6w4xn2ahik0f5ca3 foreign key (user_state_id) references user_state;
alter table if exists users
    add constraint FKmi5y7n2upe24nkpgnnns2d1a foreign key (user_state_id) references user_state;